version: '3'
services:
  chatbot:
    image: 'denoland/deno:ubuntu-1.33.4'
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    command: 'deno run --allow-env --allow-net --allow-read --allow-write index.ts'